config/routes.rb
Rails.application.routes.draw do
  root 'application#index'
  get  '/login',     to: 'sessions#new'
  post '/login',     to: 'sessions#create'
  delete '/logout',     to: 'sessions#destroy'
  resources 'applications' do
    collection do
      post :sort
    end
  end
end

app/models/application.rb
class Application < ApplicationRecord
    has_many :user_applications
    has_many :users, through: :user_applications
    validates :name, presence: true
    validates :description, presence: true
    validates :color, presence: true
    validates :default_status, :inclusion => [true, false]
    validates :link, presence: true
    acts_as_list
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_applications
    has_many :applications, through: :user_applications
    validates :login, presence: true
    validates :password, presence: true
end

app/models/user_application.rb
class UserApplication < ApplicationRecord
    belongs_to :user
    belongs_to :application
    validates_uniqueness_of :application_id, :scope => :user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationsHelper
    include SessionsHelper

    def index
        redirect_to "/login"
    end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
    def index
        user = current_user
        @applications = user.applications.order(:position)
        @application = Application.new
    end

    def create
        user = current_user
        begin
            params[:application][:id].each do |id|
                user.applications << Application.find_by(id: id) unless id == ""
            end
        rescue => exception
            flash[:danger] = exception.message
        end
        redirect_to "/applications"
    end

    def sort
        params[:application].each_with_index do |id, index|
            Application.where(id: id).update_all(position: index + 1)
        end

        head :ok
    end

    def destroy
        user = current_user
        app = Application.find_by(id: params[:id])
        user.applications.delete(app)
        redirect_to "/applications"
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.find_by(login: params[:session][:login])
        if @user && authenticate
            log_in(@user)
            redirect_to "/applications"
        else
            flash[:danger] = "Username or password is invalid."
            redirect_to "/login"
        end 
    end

    def destroy
        log_out
        redirect_to "/login"
    end

    private

      def authenticate
          @user.password == params[:session][:password]
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    def log_out
        session.delete(:user_id)
    end
end

app/views/applications/_all_applications_form.html.erb
<%= form_for @application do |f| %>
    <ul class="list-unstyled">
        <%= f.collection_check_boxes(:id, Application.all, :id, :name, {:multiple => true}) do |box| %>
            <li class="text-white"><%= box.check_box %>          <%= box.label %></li>
        <% end %>
        <%= f.submit("Add app") %>
    </ul>
<% end %>

app/views/applications/_application_cards.html.erb
<div class="row" data-url="<%= sort_applications_path %>">
    <% @applications.each do |app| %>
        <div class="col-md-4" id=<%= dom_id(app) %>>
            <div class="card mb-4 shadow-sm">
              <p class="card-text"><%= app.name %> -- <%=app.description %></p>
                <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="<%= app.color.downcase %>"/><text x="50%" y="50%" dy=".3em">Thumbnail</text></svg>
                  <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center">
                      <div class="btn-group">
                        <%= link_to "Launch", app.link, class: "btn btn-sm btn-outline-secondary", target: "_blank" %>
                        <%= link_to "Remove", application_path(app), class: "btn btn-sm btn-outline-secondary", method: :delete, data: {confirm: "Are you sure about this?"} %>
                      </div>
                   </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/applications/_header.html.erb
<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">All apps</h4>
              <%= link_to("Sign Out", logout_path, method: :delete, class: "nav-link") %>
            </div>
            <div class="col-sm-4 offset-md-1 py-4" >
              <%= render 'all_applications_form' %>
            </div>
        </div>
     </div>
  </div>
  <%= render 'navbar' %>
</header>

app/views/applications/_navbar.html.erb
<div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <strong>Dashboard</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>

app/views/applications/index.html.erb
<%= render 'header' %>
<main role="main">
  <div class="album py-5 bg-light">
    <div class="container">
      <%= render 'application_cards' %>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dashboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
  </body>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</html>